site_name: Parthiban Rajendran
docs_dir: mkdocs/docs/
plugins:
    - search
theme: 
  name: 'readthedocs'
  custom_dir: 'mkdocs/custom_theme/'
  prev_next_buttons_location: bottom
extra_css:
  - css/extra.css
  - css/nbheader_styles_MOD.css
  - css/pdfextra.css
nav:
    - Home: index.md
    - Notes: 
        - '01. Intro to KBAI' : 'Notes/01. Intro to KBAI.md'
        - '02. Principles of KBAI': 'Notes/02. Principles of KBAI.md'
        - '03. Semantic Networks' : 'Notes/03. Semantic Networks.md'
        - '04. Generate & Test' : 'Notes/04. Generate & Test.md'
        - '05. Means-Ends Analysis' : 'Notes/05. Means-Ends Analysis.md'
        - '06. Production Systems' : 'Notes/06. Production Systems.md'
        - '07. Frames' : 'Notes/07. Frames.md'
        - '08. Learning by Recording Cases': 'Notes/08. Learning by Recording Cases.md'
        - '09. Case based Reasoning' : 'Notes/09. Case based Reasoning.md'
        - '10. Incremental Concept Learning' : 'Notes/10. Incremental Concept Learning.md'
        - '11. Classification' : 'Notes/11. Classification.md'
        - '12. Logic' : 'Notes/12. Logic.md'
        - '13. Planning' : 'Notes/13. Planning.md'
        - '14. Understanding' : 'Notes/14. Understanding.md'        
        - '15. Common Sense Reasoning' : 'Notes/15. Common Sense Reasoning.md'
        - '16. Scripts' : 'Notes/16. Scripts.md'
        - '17. Explanation based Learning' : 'Notes/17. Explanation based Learning.md'
        - '18. Analogical Reasoning' : 'Notes/18. Analogical Reasoning.md'
        - '19. Version Spaces' : 'Notes/19. Version Spaces.md'
        - '20. Constraint Propogation' : 'Notes/20. Constraint Propogation.md'
        - '21. Configuration' : 'Notes/21. Configuration.md'
        - '22. Diagnosis' : 'Notes/22. Diagnosis.md'
        - '23. Learning by Correcting Mistakes' : 'Notes/23. Learning by Correcting Mistakes.md'
        - '24. Meta-Reasoning.md' : 'Notes/24. Meta-Reasoning.md'
        - '25. Advanced Topics.md' : 'Notes/25. Advanced Topics.md'
    - Ebooks:
        - 'Lectures (ext link)' : 'Ebook/kbai_ebook-compressed.pdf'
    - Misc:
        - '01. Assignment Tips' : 'Misc/99. Assignment Tips.md'
        - '02. Assignment Rubric' : 'Misc/99. Assignment Rubric.md'